name: "Test Composite Action"
description: "Test Composite Action"

runs:
  using: "composite"
  steps:
    - name: "Checkout"
      uses: actions/checkout@v2

    - name: "Setup Python"
      uses: actions/setup-python@v2
      with:
        python-version: '3.9.1'

    - name: "if statement test"
      shell: bash
      run: |
        echo ${{ github.event.pull_request.merged }}
        echo "use if statement"
