name: "Composite action test"
on:
  pull_request:
    branches:
      - master
    types: [opened, synchronize, closed]

jobs:
  composite_test:
    runs-on: ubuntu-latest
    steps:
      - uses:
      - uses: actions/checkout@v2
      - uses: .github/actions
